-----BEGIN PRIVATE KEY-----
MIGTAgEAMBMGByqGSM49AgEGCCqGSM49AwEHBHkwdwIBAQQgQaiCFcCCHi4SnzCB
KIBsuPmOnh1xiXU0eNG01tkwxZCgCgYIKoZIzj0DAQehRANCAATgb/UrWPMST03P
VhklCzhMYGlBYt9KPBfy+iP2eo91gQysSUU+NhyIh9gjHXQeGbfhhRNuXCzehedL
fDjIrpmQ
-----END PRIVATE KEY-----