export const TAB_SHOW = "TAB_SHOW";
export const TAB_HIDE = "TAB_HIDE";


export const TAB_SHOWS = "TAB_SHOWS";
export const TAB_HIDES = "TAB_HIDES";

export const RECORDSTART = "RECORDSTART";
export const RECORDSTARTCOUNT = "RECORDSTARTCOUNT"
export const RECORDPAUSE = "RECORDPAUSE"
export const RECORDPAUSECOUNT = "RECORDPAUSECOUNT"
export const RECORDRESUMECOUNT="RECORDRESUMECOUNT"

export const RECORDSTOPCOUNT="RECORDSTOPCOUNT";
export const SAVEAUDIO="SAVEAUDIO";
export const RECORDPAUSE2="RECORDPAUSE2"



